2025-05-20 18:57:15,165 INFO    MainThread:2076749 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-20 18:57:15,165 INFO    MainThread:2076749 [wandb_setup.py:_flush():67] Configure stats pid to 2076749
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_setup.py:_flush():67] Loading settings from /home/alexis/.config/wandb/settings
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_setup.py:_flush():67] Loading settings from /home/alexis/Desktop/wandb/settings
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:setup_run_log_directory():662] Logging user logs to checkpoints/training_logs/Removing_colors/(Seed 2) (bis) High_translations (10) v5/wandb/run-20250520_185715-1myjtiz4/logs/debug.log
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to checkpoints/training_logs/Removing_colors/(Seed 2) (bis) High_translations (10) v5/wandb/run-20250520_185715-1myjtiz4/logs/debug-internal.log
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:init():781] calling init triggers
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:init():809] starting backend
2025-05-20 18:57:15,166 INFO    MainThread:2076749 [wandb_init.py:init():813] sending inform_init request
2025-05-20 18:57:15,173 INFO    MainThread:2076749 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-20 18:57:15,173 INFO    MainThread:2076749 [wandb_init.py:init():823] backend started and connected
2025-05-20 18:57:15,175 INFO    MainThread:2076749 [wandb_init.py:init():915] updated telemetry
2025-05-20 18:57:15,176 INFO    MainThread:2076749 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-20 18:57:16,009 INFO    MainThread:2076749 [wandb_init.py:init():1014] starting run threads in backend
2025-05-20 18:57:16,382 INFO    MainThread:2076749 [wandb_run.py:_console_start():2454] atexit reg
2025-05-20 18:57:16,383 INFO    MainThread:2076749 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-20 18:57:16,383 INFO    MainThread:2076749 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-20 18:57:16,384 INFO    MainThread:2076749 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-20 18:57:16,387 INFO    MainThread:2076749 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-20 18:57:16,388 INFO    MainThread:2076749 [wandb_run.py:_config_callback():1327] config_cb None None {'temperature': 1, 'alpha': 1, 'encoder_size': 256, 'decoder_size': 256, 'encoder_layers': 2, 'decoder_layers': 2, 'latent_dim': 12, 'lr_base': 1e-05, 'max_lr': 0.00015, 'weight_decay': 1e-06, 'max_steps': 300000, 'batch_size': 2056, 'seed': 2, 'exclude_colors': True}
2025-05-20 18:57:17,629 INFO    MainThread:2076749 [wandb_run.py:_config_callback():1327] config_cb None None {'optim_lr': 1e-05, 'optim_weight_decay': 1e-06, 'scheduler_args': None, 'workspace_dim': 12, 'loss_coefs': {'cycles': 10.0, 'contrastives': 0.1, 'demi_cycles': 1.0, 'translations': 1.0}, 'learn_logit_scale': False, 'fusion_activation_fn': 'tanh'}
2025-05-20 18:59:23,636 INFO    MsgRouterThr:2076749 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-20 18:59:25,685 ERROR   MainThread:2076749 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 18:59:25,689 ERROR   MainThread:2076749 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
